In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('heart.csv')
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [3]:
df.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [4]:
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [5]:
df.shape

(918, 12)

In [6]:
df.HeartDisease[:10]    #heartdisease -yes/no(0/1)

0    0
1    1
2    0
3    1
4    0
5    0
6    0
7    0
8    1
9    0
Name: HeartDisease, dtype: int64

In [7]:
df.describe()

Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000   
mean    53.510893  132.396514   198.799564    0.233115  136.809368   
std      9.432617   18.514154   109.384145    0.423046   25.460334   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.250000    0.000000  120.000000   
50%     54.000000  130.000000   223.000000    0.000000  138.000000   
75%     60.000000  140.000000   267.000000    0.000000  156.000000   
max     77.000000  200.000000   603.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  918.000000    918.000000  
mean     0.887364      0.553377  
std      1.066570      0.497414  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.600000      1.000000  
75%      1.500000      1.000000  
max      6.200000      1.000000

In [8]:
df['ST_Slope']

0        Up
1      Flat
2        Up
3      Flat
4        Up
       ... 
913    Flat
914    Flat
915    Flat
916    Flat
917      Up
Name: ST_Slope, Length: 918, dtype: object

In [9]:
X = df[['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope']]

In [10]:
y = df[['HeartDisease']]

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# X_scaled = scaler.fit_transform(X)

In [12]:
# checking features (categorical)
cat = df.select_dtypes(include='O').keys()
# display variabels
cat

Index(['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'], dtype='object')

In [13]:
np.unique(df['ChestPainType'])

array(['ASY', 'ATA', 'NAP', 'TA'], dtype=object)

In [14]:
np.unique(df['RestingECG'])

array(['LVH', 'Normal', 'ST'], dtype=object)

In [15]:
np.unique(df['ExerciseAngina'])

array(['N', 'Y'], dtype=object)

In [16]:
np.unique(df['ST_Slope'])

array(['Down', 'Flat', 'Up'], dtype=object)

In [17]:
np.unique(df['Sex'])

array(['F', 'M'], dtype=object)

In [18]:
#df with only calegoricals
new_df = pd.read_csv('heart.csv', usecols=cat)
new_df.head()

Sex ChestPainType RestingECG ExerciseAngina ST_Slope
0   M           ATA     Normal              N       Up
1   F           NAP     Normal              N     Flat
2   M           ATA         ST              N       Up
3   F           ASY     Normal              Y     Flat
4   M           NAP     Normal              N       Up

In [19]:
#printing number of unique values
cat_count = {}
for i in new_df.columns:
    count_dict = {}
    for j in new_df[i]:
        if j in count_dict:
            count_dict[j] += 1
        else:
            count_dict[j] = 1
    cat_count[i] = count_dict
    
cat_count    

{'Sex': {'M': 725, 'F': 193},
 'ChestPainType': {'ATA': 173, 'NAP': 203, 'ASY': 496, 'TA': 46},
 'RestingECG': {'Normal': 552, 'ST': 178, 'LVH': 188},
 'ExerciseAngina': {'N': 547, 'Y': 371},
 'ST_Slope': {'Up': 395, 'Flat': 460, 'Down': 63}}

In [20]:
dummies = pd.get_dummies(new_df)
dummies.head()

Sex_F  Sex_M  ChestPainType_ASY  ChestPainType_ATA  ChestPainType_NAP  \
0      0      1                  0                  1                  0   
1      1      0                  0                  0                  1   
2      0      1                  0                  1                  0   
3      1      0                  1                  0                  0   
4      0      1                  0                  0                  1   

   ChestPainType_TA  RestingECG_LVH  RestingECG_Normal  RestingECG_ST  \
0                 0               0                  1              0   
1                 0               0                  1              0   
2                 0               0                  0              1   
3                 0               0                  1              0   
4                 0               0                  1              0   

   ExerciseAngina_N  ExerciseAngina_Y  ST_Slope_Down  ST_Slope_Flat  \
0                 1                 0              0              0   
1                 1                 0              0              1   
2                 1                 0              0              0   
3                 0                 1              0              1   
4                 1                 0              0              0   

   ST_Slope_Up  
0            1  
1            0  
2            1  
3            0  
4            1

In [21]:
dummies.shape

(918, 14)

In [22]:
dummies = dummies.drop(['Sex_M', 'ChestPainType_TA', 'RestingECG_LVH', 'ExerciseAngina_Y', 'ST_Slope_Up'], axis=1)

In [23]:
len(dummies.columns)

9

In [24]:
final = pd.concat([df, dummies], axis=1).drop(['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'], axis=1)

In [25]:
final.head()

Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  HeartDisease  \
0   40        140          289          0    172      0.0             0   
1   49        160          180          0    156      1.0             1   
2   37        130          283          0     98      0.0             0   
3   48        138          214          0    108      1.5             1   
4   54        150          195          0    122      0.0             0   

   Sex_F  ChestPainType_ASY  ChestPainType_ATA  ChestPainType_NAP  \
0      0                  0                  1                  0   
1      1                  0                  0                  1   
2      0                  0                  1                  0   
3      1                  1                  0                  0   
4      0                  0                  0                  1   

   RestingECG_Normal  RestingECG_ST  ExerciseAngina_N  ST_Slope_Down  \
0                  1              0                 1              0   
1                  1              0                 1              0   
2                  0              1                 1              0   
3                  1              0                 0              0   
4                  1              0                 1              0   

   ST_Slope_Flat  
0              0  
1              1  
2              0  
3              1  
4              0

In [26]:
final.shape

(918, 16)

In [27]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [28]:
X = final.drop(['HeartDisease'], axis=1)
y = final['HeartDisease']

In [29]:
X_scaled = scaler.fit_transform(X)
X_scaled[0]

array([-1.4331398 ,  0.41090889,  0.82507026, -0.55134134,  1.38292822,
       -0.83243239, -0.51595242, -1.08413811,  2.07517671, -0.53283777,
        0.81427482, -0.49044933,  0.8235563 , -0.27144836, -1.00218103])

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=30)

In [31]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.8369565217391305

### Use PrincipalComponent Analysis (pca) for dimensionality reduction


In [32]:
X[:10]

Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  Sex_F  \
0   40        140          289          0    172      0.0      0   
1   49        160          180          0    156      1.0      1   
2   37        130          283          0     98      0.0      0   
3   48        138          214          0    108      1.5      1   
4   54        150          195          0    122      0.0      0   
5   39        120          339          0    170      0.0      0   
6   45        130          237          0    170      0.0      1   
7   54        110          208          0    142      0.0      0   
8   37        140          207          0    130      1.5      0   
9   48        120          284          0    120      0.0      1   

   ChestPainType_ASY  ChestPainType_ATA  ChestPainType_NAP  RestingECG_Normal  \
0                  0                  1                  0                  1   
1                  0                  0                  1                  1   
2                  0                  1                  0                  0   
3                  1                  0                  0                  1   
4                  0                  0                  1                  1   
5                  0                  0                  1                  1   
6                  0                  1                  0                  1   
7                  0                  1                  0                  1   
8                  1                  0                  0                  1   
9                  0                  1                  0                  1   

   RestingECG_ST  ExerciseAngina_N  ST_Slope_Down  ST_Slope_Flat  
0              0                 1              0              0  
1              0                 1              0              1  
2              1                 1              0              0  
3              0                 0              0              1  
4              0                 1              0              0  
5              0                 1              0              0  
6              0                 1              0              0  
7              0                 1              0              0  
8              0                 0              0              1  
9              0                 1              0              0

### Use components such that 95% of variance is retained

In [33]:
from sklearn.decomposition import PCA
pca = PCA(0.95)
X_pca = pca.fit_transform(X)
X_pca.shape

(918, 2)

In [34]:
pca.explained_variance_ratio_

array([0.92024537, 0.04913132])

In [35]:
pca.n_components_

2

In [36]:
X_pca

array([[ 92.31137687, -29.44520439],
       [-17.14314815, -13.74311755],
       [ 81.90677719,  38.22459076],
       ...,
       [-69.00382233,  17.33444162],
       [ 39.20727331, -33.59903402],
       [-21.43749287, -37.21627464]])

In [37]:
X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=30)

In [38]:
model_pca = LogisticRegression()
model_pca.fit(X_train_pca, y_train)
model_pca.score(X_test_pca, y_test)

0.7010869565217391

#### Let's now select only two components

In [39]:
pca_2 = PCA(n_components=2)
X_pca_2 = pca.fit_transform(X)
X_pca_2.shape

(918, 2)

In [40]:
X_pca_2

array([[ 92.31137687, -29.44520439],
       [-17.14314815, -13.74311755],
       [ 81.90677719,  38.22459076],
       ...,
       [-69.00382233,  17.33444162],
       [ 39.20727331, -33.59903402],
       [-21.43749287, -37.21627464]])

In [41]:
pca.explained_variance_ratio_

array([0.92024537, 0.04913132])

In [42]:
#train-test-split
X_train_pca_2, X_test_pca_2, y_train, y_test = train_test_split(X_pca_2, y, test_size=0.2, random_state=30)

model_pca_2 = LogisticRegression(max_iter=1000)
model_pca_2.fit(X_train_pca_2, y_train)
model_pca_2.score(X_test_pca_2, y_test)

0.7010869565217391